### PR TITLE
Added FontAwesome to allow for offline symbols

### PR DESCRIPTION
**Pull request by Bobbabo**

### CODE REVIEW

**Comment by Bobbabo** [comment]
image

**Review by lucasfth — CHANGES_REQUESTED** [review]
Most of these css files seem to go unused, including `all.min.css`.
Have I missed something?
If not then these unused css files should be removed.

**Comment by Bobbabo** [comment]
> Most of these css files seem to go unused, including `all.min.css`. Have I missed something? If not then these unused css files should be removed.

Thanks for noticing. I have now removed the files that were unused 😇

**Review by lucasfth — APPROVED** [review]
LGTM🚀

**Pull request merged**
